[package]
name = "rust-workspace-bin"
description = ""
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rust-workspace-lib.workspace = true

argh.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
