[package]
name = "jungle"
version.workspace = true
edition.workspace = true

[[bin]]
name = "jungle"
path = "src/jungle.rs"

[dependencies]
lib.workspace = true
bevy.workspace = true
argh.workspace = true
