[package]
name = "example"
version.workspace = true
edition.workspace = true

[[bin]]
name = "example"
path = "src/example.rs"

[dependencies]
lib.workspace = true
bevy.workspace = true
argh.workspace = true
