[package]
name = "berlinrat"
version.workspace = true
edition.workspace = true

[[bin]]
name = "berlinrat"
path = "src/berlinrat.rs"

[dependencies]
lib.workspace = true
bevy.workspace = true
argh.workspace = true
